import { Asset } from './types';

export const ASSETS: Asset[] = [
  { id: 'btc', symbol: 'BTC', name: 'Bitcoin', icon: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png', color: '#F7931A', price: 65000, networks: ['Bitcoin', 'Lightning'] },
  { id: 'eth', symbol: 'ETH', name: 'Ethereum', icon: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png', color: '#627EEA', price: 3500, networks: ['ERC-20', 'Arbitrum', 'Optimism', 'Base'] },
  { id: 'usdt', symbol: 'USDT', name: 'Tether', icon: 'https://assets.coingecko.com/coins/images/325/small/tether.png', color: '#26A17B', price: 1, networks: ['TRC-20', 'ERC-20', 'BEP-20', 'Solana'] },
  { id: 'sol', symbol: 'SOL', name: 'Solana', icon: 'https://assets.coingecko.com/coins/images/4128/small/solana.png', color: '#14F195', price: 140, networks: ['Solana'] },
  { id: 'ada', symbol: 'ADA', name: 'Cardano', icon: 'https://assets.coingecko.com/coins/images/975/small/cardano.png', color: '#0033AD', price: 0.45, networks: ['Cardano'] },
  { id: 'shib', symbol: 'SHIB', name: 'Shiba Inu', icon: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png', color: '#FFA500', price: 0.000025, networks: ['ERC-20', 'Shibarium'] },
  { id: 'avax', symbol: 'AVAX', name: 'Avalanche', icon: 'https://assets.coingecko.com/coins/images/12559/small/avalanche.png', color: '#E84142', price: 35, networks: ['C-Chain', 'P-Chain'] },
  { id: 'dot', symbol: 'DOT', name: 'Polkadot', icon: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png', color: '#E6007A', price: 7, networks: ['Polkadot'] },
  { id: 'link', symbol: 'LINK', name: 'Chainlink', icon: 'https://assets.coingecko.com/coins/images/877/small/chainlink.png', color: '#2A5ADA', price: 18, networks: ['ERC-20', 'Arbitrum', 'Polygon'] },
  { id: 'bch', symbol: 'BCH', name: 'Bitcoin Cash', icon: 'https://assets.coingecko.com/coins/images/780/small/bitcoin-cash.png', color: '#8BC34A', price: 450, networks: ['Bitcoin Cash'] },
  { id: 'hype', symbol: 'HYPE', name: 'Hyperliquid', icon: 'https://assets.coingecko.com/coins/images/35000/small/hyperliquid.png', color: '#00F3FF', price: 12, networks: ['Hyperliquid'] },
  { id: 'pol', symbol: 'POL', name: 'Polygon', icon: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png', color: '#8247E5', price: 0.7, networks: ['Polygon', 'zkEVM'] },
  { id: 'ltc', symbol: 'LTC', name: 'Litecoin', icon: 'https://assets.coingecko.com/coins/images/2/small/litecoin.png', color: '#345D9D', price: 85, networks: ['Litecoin'] },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol', icon: 'https://assets.coingecko.com/coins/images/10365/small/near.png', color: '#000000', price: 7, networks: ['NEAR'] },
  { id: 'uni', symbol: 'UNI', name: 'Uniswap', icon: 'https://assets.coingecko.com/coins/images/12504/small/uniswap.png', color: '#FF007A', price: 11, networks: ['ERC-20', 'Arbitrum', 'Polygon'] },
  { id: 'pepe', symbol: 'PEPE', name: 'PEPE', icon: 'https://assets.coingecko.com/coins/images/29850/small/pepe.png', color: '#43A047', price: 0.000008, networks: ['ERC-20'] },
  { id: 'dai', symbol: 'DAI', name: 'Dai', icon: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png', color: '#F5AC37', price: 1, networks: ['ERC-20', 'Optimism', 'Arbitrum'] },
  { id: 'icp', symbol: 'ICP', name: 'Internet Computer', icon: 'https://assets.coingecko.com/coins/images/14495/small/Internet_Computer_logo.png', color: '#292A2E', price: 13, networks: ['ICP'] },
  { id: 'sui', symbol: 'SUI', name: 'Sui', icon: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.png', color: '#6FBCF0', price: 1.6, networks: ['Sui'] },
  { id: 'apt', symbol: 'APT', name: 'Aptos', icon: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png', color: '#000000', price: 12, networks: ['Aptos'] },
  { id: 'xmr', symbol: 'XMR', name: 'Monero', icon: 'https://assets.coingecko.com/coins/images/69/small/monero_logo.png', color: '#FF6600', price: 140, networks: ['Monero'] },
  { id: 'stx', symbol: 'STX', name: 'Stacks', icon: 'https://assets.coingecko.com/coins/images/2069/small/Stacks_logo_full.png', color: '#5546FF', price: 3.2, networks: ['Stacks'] },
  { id: 'xlm', symbol: 'XLM', name: 'Stellar', icon: 'https://assets.coingecko.com/coins/images/100/small/stellar.png', color: '#000000', price: 0.13, networks: ['Stellar'] },
  { id: 'render', symbol: 'RENDER', name: 'Render', icon: 'https://assets.coingecko.com/coins/images/11636/small/render.png', color: '#000000', price: 10, networks: ['ERC-20', 'Solana'] },
  { id: 'okb', symbol: 'OKB', name: 'OKB', icon: 'https://assets.coingecko.com/coins/images/4463/small/okb.png', color: '#3075EE', price: 55, networks: ['OKC'] },
  { id: 'atom', symbol: 'ATOM', name: 'Cosmos', icon: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png', color: '#2E3148', price: 11, networks: ['Cosmos'] },
  { id: 'op', symbol: 'OP', name: 'Optimism', icon: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png', color: '#FF0420', price: 3.5, networks: ['Optimism'] },
  { id: 'arb', symbol: 'ARB', name: 'Arbitrum', icon: 'https://assets.coingecko.com/coins/images/16547/small/arbitrum.png', color: '#28A0F0', price: 1.6, networks: ['Arbitrum'] },
  { id: 'fil', symbol: 'FIL', name: 'Filecoin', icon: 'https://assets.coingecko.com/coins/images/12817/small/filecoin.png', color: '#0090FF', price: 9, networks: ['Filecoin'] },
  { id: 'imx', symbol: 'IMX', name: 'Immutable', icon: 'https://assets.coingecko.com/coins/images/17233/small/immutableX-symbol-BLK-RGB.png', color: '#000000', price: 2.8, networks: ['Immutable'] },
  { id: 'inj', symbol: 'INJ', name: 'Injective', icon: 'https://assets.coingecko.com/coins/images/12882/small/Secondary_Symbol.png', color: '#00A3FF', price: 35, networks: ['Injective'] },
  { id: 'hbar', symbol: 'HBAR', name: 'Hedera', icon: 'https://assets.coingecko.com/coins/images/3688/small/hbar.png', color: '#000000', price: 0.1, networks: ['Hedera'] },
  { id: 'cro', symbol: 'CRO', name: 'Cronos', icon: 'https://assets.coingecko.com/coins/images/7310/small/cro.png', color: '#002D72', price: 0.15, networks: ['Cronos'] },
  { id: 'vet', symbol: 'VET', name: 'VeChain', icon: 'https://assets.coingecko.com/coins/images/1167/small/VeChain-Logo-768x725.png', color: '#15BDFF', price: 0.04, networks: ['VeChain'] },
  { id: 'tia', symbol: 'TIA', name: 'Celestia', icon: 'https://assets.coingecko.com/coins/images/31967/small/tia.png', color: '#7B2BF9', price: 14, networks: ['Celestia'] },
  { id: 'sky', symbol: 'SKY', name: 'Sky', icon: 'https://assets.coingecko.com/coins/images/99/small/maker.png', color: '#1AAB9B', price: 2800, networks: ['ERC-20'] },
  { id: 'ar', symbol: 'AR', name: 'Arweave', icon: 'https://assets.coingecko.com/coins/images/4343/small/arweave.png', color: '#222326', price: 35, networks: ['Arweave'] },
  { id: 'wld', symbol: 'WLD', name: 'Worldcoin', icon: 'https://assets.coingecko.com/coins/images/31069/small/worldcoin.png', color: '#000000', price: 8, networks: ['Optimism'] },
  { id: 'ldo', symbol: 'LDO', name: 'Lido DAO', icon: 'https://assets.coingecko.com/coins/images/13573/small/Lido_DAO.png', color: '#00A3FF', price: 2.5, networks: ['ERC-20'] },
  { id: 'grt', symbol: 'GRT', name: 'The Graph', icon: 'https://assets.coingecko.com/coins/images/13397/small/Graph_Token.png', color: '#6747ED', price: 0.4, networks: ['ERC-20', 'Arbitrum'] },
  { id: 'rune', symbol: 'RUNE', name: 'THORChain', icon: 'https://assets.coingecko.com/coins/images/6595/small/thorchain.png', color: '#00EFB8', price: 8, networks: ['THORChain'] },
  { id: 'tao', symbol: 'TAO', name: 'Bittensor', icon: 'https://assets.coingecko.com/coins/images/28562/small/bittensor-logo.png', color: '#000000', price: 600, networks: ['Bittensor'] },
  { id: 'ftm', symbol: 'FTM', name: 'Fantom', icon: 'https://assets.coingecko.com/coins/images/4001/small/Fantom.png', color: '#1969FF', price: 1, networks: ['Fantom'] },
  { id: 'sei', symbol: 'SEI', name: 'Sei', icon: 'https://assets.coingecko.com/coins/images/30632/small/sei.png', color: '#B22222', price: 0.8, networks: ['Sei'] },
  { id: 'mnt', symbol: 'MNT', name: 'Mantle', icon: 'https://assets.coingecko.com/coins/images/30980/small/mantle.png', color: '#000000', price: 1.2, networks: ['Mantle'] },
  { id: 'algo', symbol: 'ALGO', name: 'Algorand', icon: 'https://assets.coingecko.com/coins/images/4380/small/download.png', color: '#000000', price: 0.25, networks: ['Algorand'] },
  { id: 'beam', symbol: 'BEAM', name: 'Beam', icon: 'https://assets.coingecko.com/coins/images/32811/small/beam-logo.png', color: '#000000', price: 0.03, networks: ['Beam'] },
  { id: 'jup', symbol: 'JUP', name: 'Jupiter', icon: 'https://assets.coingecko.com/coins/images/34188/small/jup.png', color: '#222222', price: 1.2, networks: ['Solana'] },
  { id: 'ena', symbol: 'ENA', name: 'Ethena', icon: 'https://assets.coingecko.com/coins/images/36369/small/ethena.png', color: '#000000', price: 0.9, networks: ['ERC-20'] },
  { id: 'core', symbol: 'CORE', name: 'Core', icon: 'https://assets.coingecko.com/coins/images/28938/small/core.png', color: '#000000', price: 2.5, networks: ['Core'] },
  { id: 'bonk', symbol: 'BONK', name: 'Bonk', icon: 'https://assets.coingecko.com/coins/images/28600/small/bonk.png', color: '#F5A623', price: 0.000025, networks: ['Solana'] },
  { id: 'floki', symbol: 'FLOKI', name: 'FLOKI', icon: 'https://assets.coingecko.com/coins/images/16746/small/floki.png', color: '#FFB800', price: 0.0002, networks: ['ERC-20', 'BEP-20'] },
  { id: 'pyth', symbol: 'PYTH', name: 'Pyth Network', icon: 'https://assets.coingecko.com/coins/images/31924/small/pyth.png', color: '#000000', price: 0.9, networks: ['Solana'] },
  { id: 'gala', symbol: 'GALA', name: 'Gala', icon: 'https://assets.coingecko.com/coins/images/12493/small/GALA-01.png', color: '#000000', price: 0.06, networks: ['ERC-20'] },
  { id: 'qnt', symbol: 'QNT', name: 'Quant', icon: 'https://assets.coingecko.com/coins/images/3370/small/quant.png', color: '#000000', price: 120, networks: ['ERC-20'] },
  { id: 'eos', symbol: 'EOS', name: 'EOS', icon: 'https://assets.coingecko.com/coins/images/738/small/eos.png', color: '#000000', price: 1, networks: ['EOS'] },
  { id: 'xtz', symbol: 'XTZ', name: 'Tezos', icon: 'https://assets.coingecko.com/coins/images/976/small/tezos.png', color: '#2C7DF7', price: 1.2, networks: ['Tezos'] },
  { id: 'flow', symbol: 'FLOW', name: 'Flow', icon: 'https://assets.coingecko.com/coins/images/13446/small/flow.png', color: '#00EF8B', price: 1.3, networks: ['Flow'] },
  { id: 'pendle', symbol: 'PENDLE', name: 'Pendle', icon: 'https://assets.coingecko.com/coins/images/16145/small/pendle.png', color: '#000000', price: 6, networks: ['ERC-20', 'Arbitrum'] },
  { id: 'jasmy', symbol: 'JASMY', name: 'JasmyCoin', icon: 'https://assets.coingecko.com/coins/images/13876/small/Jasmy.png', color: '#000000', price: 0.02, networks: ['ERC-20'] },
  { id: 'axs', symbol: 'AXS', name: 'Axie Infinity', icon: 'https://assets.coingecko.com/coins/images/13029/small/axie_infinity.png', color: '#0084FF', price: 10, networks: ['ERC-20', 'Ronin'] },
  { id: 'mana', symbol: 'MANA', name: 'Decentraland', icon: 'https://assets.coingecko.com/coins/images/878/small/decentraland.png', color: '#FF2D55', price: 0.6, networks: ['ERC-20'] },
  { id: 'sand', symbol: 'SAND', name: 'The Sandbox', icon: 'https://assets.coingecko.com/coins/images/12129/small/sandbox.png', color: '#00ADEF', price: 0.6, networks: ['ERC-20'] },
  { id: 'egld', symbol: 'EGLD', name: 'MultiversX', icon: 'https://assets.coingecko.com/coins/images/12371/small/egld.png', color: '#000000', price: 55, networks: ['MultiversX'] },
  { id: 'aave', symbol: 'AAVE', name: 'Aave', icon: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png', color: '#B6509E', price: 120, networks: ['ERC-20', 'Polygon', 'Arbitrum'] },
  { id: 'snx', symbol: 'SNX', name: 'Synthetix', icon: 'https://assets.coingecko.com/coins/images/3406/small/SNX.png', color: '#00D1FF', price: 4, networks: ['ERC-20', 'Optimism'] },
  { id: 'dydx', symbol: 'DYDX', name: 'dYdX', icon: 'https://assets.coingecko.com/coins/images/17500/small/dydx.png', color: '#6966FF', price: 3, networks: ['dYdX'] },
  { id: 'neo', symbol: 'NEO', name: 'Neo', icon: 'https://assets.coingecko.com/coins/images/480/small/neo.png', color: '#00E599', price: 15, networks: ['Neo'] },
  { id: 'hnt', symbol: 'HNT', name: 'Helium', icon: 'https://assets.coingecko.com/coins/images/4284/small/Helium_HNT.png', color: '#474DFF', price: 6, networks: ['Solana'] },
  { id: 'iota', symbol: 'IOTA', name: 'IOTA', icon: 'https://assets.coingecko.com/coins/images/692/small/IOTA_Logo.png', color: '#000000', price: 0.3, networks: ['IOTA'] },
  { id: 'kava', symbol: 'KAVA', name: 'Kava', icon: 'https://assets.coingecko.com/coins/images/9761/small/kava.png', color: '#FF5B5C', price: 0.9, networks: ['Kava'] },
  { id: 'mina', symbol: 'MINA', name: 'Mina', icon: 'https://assets.coingecko.com/coins/images/15628/small/mina-protocol-logo.png', color: '#FF7334', price: 1.2, networks: ['Mina'] },
  { id: 'cfx', symbol: 'CFX', name: 'Conflux', icon: 'https://assets.coingecko.com/coins/images/13079/small/conflux.png', color: '#1E55F0', price: 0.4, networks: ['Conflux'] },
  { id: 'chz', symbol: 'CHZ', name: 'Chiliz', icon: 'https://assets.coingecko.com/coins/images/8834/small/CHZ.png', color: '#CD0124', price: 0.15, networks: ['Chiliz'] },
  { id: 'ron', symbol: 'RON', name: 'Ronin', icon: 'https://assets.coingecko.com/coins/images/22745/small/ronin.png', color: '#1233D5', price: 4, networks: ['Ronin'] },
  { id: 'trump', symbol: 'TRUMP', name: 'Official Trump', icon: 'https://assets.coingecko.com/coins/images/34532/small/trump.png', color: '#000000', price: 5, networks: ['ERC-20', 'Solana'] },
  { id: 'gt', symbol: 'GT', name: 'GateToken', icon: 'https://assets.coingecko.com/coins/images/8183/small/gt.png', color: '#2354AD', price: 8, networks: ['OKC'] },
  { id: 'kcs', symbol: 'KCS', name: 'KuCoin Token', icon: 'https://assets.coingecko.com/coins/images/1047/small/kucoin-shares.png', color: '#0093DD', price: 12, networks: ['KCS'] },
  { id: 'flr', symbol: 'FLR', name: 'Flare', icon: 'https://assets.coingecko.com/coins/images/13424/small/flare.png', color: '#E1192E', price: 0.04, networks: ['Flare'] },
  { id: 'cc', symbol: 'CC', name: 'Canton Network', icon: 'https://assets.coingecko.com/coins/images/35001/small/canton.png', color: '#000000', price: 1, networks: ['Canton'] },
  { id: 'frax', symbol: 'FRAX', name: 'Frax', icon: 'https://assets.coingecko.com/coins/images/13422/small/frax_logo.png', color: '#000000', price: 1, networks: ['ERC-20'] },
  { id: 'pyusd', symbol: 'PYUSD', name: 'PayPal USD', icon: 'https://assets.coingecko.com/coins/images/31212/small/paypal-usd.png', color: '#003087', price: 1, networks: ['ERC-20', 'Solana'] },
  { id: 'bgb', symbol: 'BGB', name: 'Bitget Token', icon: 'https://assets.coingecko.com/coins/images/11610/small/bgb.png', color: '#00F0FF', price: 1.2, networks: ['ERC-20'] },
  { id: 'ray', symbol: 'RAY', name: 'Raydium', icon: 'https://assets.coingecko.com/coins/images/13928/small/ray.png', color: '#000000', price: 2.5, networks: ['Solana'] },
  { id: 'btt', symbol: 'BTT', name: 'BitTorrent', icon: 'https://assets.coingecko.com/coins/images/22457/small/bttc.png', color: '#000000', price: 0.0000015, networks: ['TRC-20'] },
  { id: 'lunc', symbol: 'LUNC', name: 'Terra Classic', icon: 'https://assets.coingecko.com/coins/images/25742/small/luna_classic.png', color: '#FFD700', price: 0.00015, networks: ['Terra'] },
  { id: '1inch', symbol: '1INCH', name: '1inch', icon: 'https://assets.coingecko.com/coins/images/13469/small/1inch-token.png', color: '#1B314F', price: 0.6, networks: ['ERC-20', 'BSC'] },
  { id: 'cake', symbol: 'CAKE', name: 'PancakeSwap', icon: 'https://assets.coingecko.com/coins/images/12632/small/pancakeswap.png', color: '#D1884F', price: 4, networks: ['BEP-20'] },
  { id: 'nexo', symbol: 'NEXO', name: 'Nexo', icon: 'https://assets.coingecko.com/coins/images/3695/small/nexo.png', color: '#1A41FF', price: 1.4, networks: ['ERC-20'] },
  { id: 'sun', symbol: 'SUN', name: 'SUN', icon: 'https://assets.coingecko.com/coins/images/12441/small/sun.png', color: '#FF0000', price: 0.015, networks: ['TRC-20'] },
  { id: 'river', symbol: 'RIVER', name: 'RIVER', icon: 'https://assets.coingecko.com/coins/images/35002/small/river.png', color: '#000000', price: 0.5, networks: ['ERC-20'] },
  { id: 'nft', symbol: 'NFT', name: 'APENFT', icon: 'https://assets.coingecko.com/coins/images/15687/small/apenft.png', color: '#000000', price: 0.0000005, networks: ['TRC-20'] },
  { id: 'gno', symbol: 'GNO', name: 'Gnosis', icon: 'https://assets.coingecko.com/coins/images/1102/small/gnosis-logo.png', color: '#00A6C4', price: 350, networks: ['Gnosis'] },
  { id: 'crv', symbol: 'CRV', name: 'Curve DAO', icon: 'https://assets.coingecko.com/coins/images/12124/small/Curve.png', color: '#000000', price: 0.6, networks: ['ERC-20'] },
  { id: 'theta', symbol: 'THETA', name: 'Theta Network', icon: 'https://assets.coingecko.com/coins/images/2538/small/theta-token-logo.png', color: '#2AB8E6', price: 3, networks: ['Theta'] },
  { id: 'mkr', symbol: 'MKR', name: 'Maker', icon: 'https://assets.coingecko.com/coins/images/99/small/maker.png', color: '#1AAB9B', price: 2800, networks: ['ERC-20'] },
  { id: 'lrc', symbol: 'LRC', name: 'Loopring', icon: 'https://assets.coingecko.com/coins/images/913/small/LRC.png', color: '#1C60FF', price: 0.4, networks: ['Loopring'] },
  { id: 'enj', symbol: 'ENJ', name: 'Enjin Coin', icon: 'https://assets.coingecko.com/coins/images/1100/small/enjin_coin.png', color: '#624DBF', price: 0.5, networks: ['Enjin'] },
  { id: 'bat', symbol: 'BAT', name: 'Basic Attention Token', icon: 'https://assets.coingecko.com/coins/images/677/small/basic-attention-token.png', color: '#FF5000', price: 0.35, networks: ['ERC-20'] },
  { id: 'comp', symbol: 'COMP', name: 'Compound', icon: 'https://assets.coingecko.com/coins/images/10775/small/compound.png', color: '#00D395', price: 80, networks: ['ERC-20'] },
  { id: 'zrx', symbol: 'ZRX', name: '0x', icon: 'https://assets.coingecko.com/coins/images/863/small/0x.png', color: '#302C2C', price: 0.6, networks: ['ERC-20'] },
  { id: 'omg', symbol: 'OMG', name: 'OMG Network', icon: 'https://assets.coingecko.com/coins/images/776/small/OMG.png', color: '#1A53F0', price: 1.2, networks: ['ERC-20'] },
  { id: 'zec', symbol: 'ZEC', name: 'Zcash', icon: 'https://assets.coingecko.com/coins/images/486/small/zcash-logo.png', color: '#F4B728', price: 35, networks: ['Zcash'] },
  { id: 'dash', symbol: 'DASH', name: 'Dash', icon: 'https://assets.coingecko.com/coins/images/19/small/dash-logo.png', color: '#008CE7', price: 40, networks: ['Dash'] },
  { id: 'dgb', symbol: 'DGB', name: 'DigiByte', icon: 'https://assets.coingecko.com/coins/images/63/small/digibyte.png', color: '#006AD2', price: 0.015, networks: ['DigiByte'] },
];

export const ADMIN_ADDRESSES: Record<string, string> = {
  BTC: 'bc1q3407ek54e5l9qpeutyggvyya7ayexvckfgk4vn',
  ETH: '0xbC4C6b145e7a042E5B7695496A92288199c7399c',
  USDT: 'TH2CTQMTYfi6jqknArpQLHdyXyJhAYJnJj',
  USDC: 'TH2CTQMTYfi6jqknArpQLHdyXyJhAYJnJj',
  SOL: '7mY3qvdBBBZh3H6FzMZqhxbMsPeBbRTWZH3qCrX3ZTXT',
  BNB: '0xbC4C6b145e7a042E5B7695496A92288199c7399c',
  ADA: 'addr1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  LTC: 'Lxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  XMR: '4xy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  XLM: 'Gxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  BCH: 'qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  SHIB: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  AVAX: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  DOT: '1xy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  LINK: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  HYPE: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  POL: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  NEAR: 'xy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh.near',
  UNI: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  PEPE: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  DAI: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
  ICP: 'xy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  SUI: '0xxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  APT: '0xxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  STX: 'SPxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',
  RENDER: '0x71C7656EC7ab88b098defB751B7401B5f6d8976F',
};

export const generateTxId = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'TX-';
  for (let i = 0; i < 4; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  result += '-';
  for (let i = 0; i < 4; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};
